[package]
name = "token-contract"
version = "0.1.0"
authors = ["Jon Huang"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "4.1.0"
near-contract-standards = "4.1.0"

[lib]
crate-type = ["cdylib"]